### PR TITLE
add stars and more reviews button

### PR DESCRIPTION
**Pull request by Paula-Yang**
Too many lines committed, thought it's time for a pr

### CODE REVIEW

**Review by frankasoto — CHANGES_REQUESTED** [review]
In your ReviewTile file, I noticed you are using _ as a variable name. As far as I know, we only use _ to start a variable name is if it is a private variable. Does this represent something specific?

**Review by frankasoto — APPROVED** [review]
I  like how you destructured the review. Makes it easy to read.

**Review by frankasoto — CHANGES_REQUESTED** [review]
Didnt realize that leaving multiple comments in different commits would overwrite what I said earlier. Look at earlier comment on what needs to be fixed/clarified

**Comment by Paula-Yang** [comment]
@frankasoto Good point! This is where I referred to a tutorial of how to make rating stars in React w/o installing packages. i also got confused and googled so I'll explain that line here:

In line 26 of ReviewTile.jsx, the map function takes a callback that's executed for each element in the array created for totalStars(which is 5 in our case).  "_ " is like a convention to indicate that we're not using the element(1,2,3,4,5) itself. We're generating stars based on the index(0 to totalStars.length -1, which is 0-4 in our case). Index helps us identify each star's position and decide whether it's filled (isActive is based on the index compared to the rating)."_" is basically like a placeholder for the current element parameter.(So it can be changed to name such as "element" I guess)

And @luckynumberthirteen yes you're right I'll definitely need to add more detailed commit comments or pseudocode from now on. Thanks for the advice!

**Review by frankasoto — APPROVED** [review]

**Pull request merged**
